-- Limpiar pizzas anteriores
DELETE FROM products WHERE category_id IN ('personal', 'medium', 'large', 'family', 'combos');

-- Insertar nuevas pizzas
INSERT INTO products (category_id, name, description, price, is_available, image_url, base_ingredients) VALUES
('family', 'Carnivora', 'Deliciosa pizza Carnivora tamaño Familiar Rectangular', 22, true, '/images/pizzas/carnivora_family.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Carnivora', 'Deliciosa pizza Carnivora tamaño grande', 16.5, true, '/images/pizzas/carnivora_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Carnivora', 'Deliciosa pizza Carnivora tamaño mediana', 12.5, true, '/images/pizzas/carnivora_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Carnivora', 'Deliciosa pizza Carnivora tamaño pequeña', 8.5, true, '/images/pizzas/carnivora_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('family', 'Charcutera', 'Deliciosa pizza Charcutera tamaño Familiar Rectangular', 22, true, '/images/pizzas/charcutera_family.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Charcutera', 'Deliciosa pizza Charcutera tamaño grande', 16.5, true, '/images/pizzas/charcutera_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Charcutera', 'Deliciosa pizza Charcutera tamaño mediana', 12.5, true, '/images/pizzas/charcutera_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Charcutera', 'Deliciosa pizza Charcutera tamaño pequeña', 8.5, true, '/images/pizzas/charcutera_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('family', 'Chorizo', 'Deliciosa pizza Chorizo tamaño Familiar Rectangular', 22, true, '/images/pizzas/chorizo_family.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Chorizo', 'Deliciosa pizza Chorizo tamaño grande', 16.5, true, '/images/pizzas/chorizo_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Chorizo', 'Deliciosa pizza Chorizo tamaño mediana', 12.5, true, '/images/pizzas/chorizo_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Chorizo', 'Deliciosa pizza Chorizo tamaño pequeña', 8.5, true, '/images/pizzas/chorizo_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('family', 'Especial De Anchoas', 'Deliciosa pizza Especial De Anchoas tamaño Familiar Rectangular', 22, true, '/images/pizzas/especial_de_anchoas_family.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Especial De Anchoas', 'Deliciosa pizza Especial De Anchoas tamaño grande', 16.5, true, '/images/pizzas/especial_de_anchoas_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Especial De Anchoas', 'Deliciosa pizza Especial De Anchoas tamaño mediana', 12.5, true, '/images/pizzas/especial_de_anchoas_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Especial De Anchoas', 'Deliciosa pizza Especial De Anchoas tamaño pequeña', 8.5, true, '/images/pizzas/especial_de_anchoas_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('family', 'Especial De Chorizo', 'Deliciosa pizza Especial De Chorizo tamaño Familiar Rectangular', 22, true, '/images/pizzas/especial_de_chorizo_family.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Especial De Chorizo', 'Deliciosa pizza Especial De Chorizo tamaño grande', 16.5, true, '/images/pizzas/especial_de_chorizo_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Especial De Chorizo', 'Deliciosa pizza Especial De Chorizo tamaño mediana', 12.5, true, '/images/pizzas/especial_de_chorizo_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Especial De Chorizo', 'Deliciosa pizza Especial De Chorizo tamaño pequeña', 8.5, true, '/images/pizzas/especial_de_chorizo_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('family', 'Jamon Y Queso', 'Deliciosa pizza Jamon Y Queso tamaño Familiar Rectangular', 22, true, '/images/pizzas/jamon_y_queso_family.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Jamon Y Queso', 'Deliciosa pizza Jamon Y Queso tamaño grande', 16.5, true, '/images/pizzas/jamon_y_queso_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Jamon Y Queso', 'Deliciosa pizza Jamon Y Queso tamaño mediana', 12.5, true, '/images/pizzas/jamon_y_queso_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Jamon Y Queso', 'Deliciosa pizza Jamon Y Queso tamaño pequeña', 8.5, true, '/images/pizzas/jamon_y_queso_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('family', 'Margarita', 'Deliciosa pizza Margarita tamaño Familiar Rectangular', 22, true, '/images/pizzas/margarita_family.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Margarita', 'Deliciosa pizza Margarita tamaño grande', 16.5, true, '/images/pizzas/margarita_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Margarita', 'Deliciosa pizza Margarita tamaño mediana', 12.5, true, '/images/pizzas/margarita_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Margarita', 'Deliciosa pizza Margarita tamaño pequeña', 8.5, true, '/images/pizzas/margarita_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Meat', 'Deliciosa pizza Meat tamaño grande', 16.5, true, '/images/pizzas/meat_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Meat', 'Deliciosa pizza Meat tamaño mediana', 12.5, true, '/images/pizzas/meat_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Meat', 'Deliciosa pizza Meat tamaño pequeña', 8.5, true, '/images/pizzas/meat_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('family', 'Pepperoni', 'Deliciosa pizza Pepperoni tamaño Familiar Rectangular', 22, true, '/images/pizzas/pepperoni_family.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Pepperoni', 'Deliciosa pizza Pepperoni tamaño grande', 16.5, true, '/images/pizzas/pepperoni_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Pepperoni', 'Deliciosa pizza Pepperoni tamaño mediana', 12.5, true, '/images/pizzas/pepperoni_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Pepperoni', 'Deliciosa pizza Pepperoni tamaño pequeña', 8.5, true, '/images/pizzas/pepperoni_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('family', 'Primavera', 'Deliciosa pizza Primavera tamaño Familiar Rectangular', 22, true, '/images/pizzas/primavera_family.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Primavera', 'Deliciosa pizza Primavera tamaño grande', 16.5, true, '/images/pizzas/primavera_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Primavera', 'Deliciosa pizza Primavera tamaño mediana', 12.5, true, '/images/pizzas/primavera_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Primavera', 'Deliciosa pizza Primavera tamaño pequeña', 8.5, true, '/images/pizzas/primavera_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('family', 'Super Meat', 'Deliciosa pizza Super Meat tamaño Familiar Rectangular', 22, true, '/images/pizzas/super_meat_family.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Super Meat', 'Deliciosa pizza Super Meat tamaño grande', 16.5, true, '/images/pizzas/super_meat_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Super Meat', 'Deliciosa pizza Super Meat tamaño mediana', 12.5, true, '/images/pizzas/super_meat_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Super Meat', 'Deliciosa pizza Super Meat tamaño pequeña', 8.5, true, '/images/pizzas/super_meat_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('family', 'Tocineta', 'Deliciosa pizza Tocineta tamaño Familiar Rectangular', 22, true, '/images/pizzas/tocineta_family.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Tocineta', 'Deliciosa pizza Tocineta tamaño grande', 16.5, true, '/images/pizzas/tocineta_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Tocineta', 'Deliciosa pizza Tocineta tamaño mediana', 12.5, true, '/images/pizzas/tocineta_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Tocineta', 'Deliciosa pizza Tocineta tamaño pequeña', 8.5, true, '/images/pizzas/tocineta_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('family', 'Vegetariana', 'Deliciosa pizza Vegetariana tamaño Familiar Rectangular', 22, true, '/images/pizzas/vegetariana_family.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('large', 'Vegetariana', 'Deliciosa pizza Vegetariana tamaño grande', 16.5, true, '/images/pizzas/vegetariana_large.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('medium', 'Vegetariana', 'Deliciosa pizza Vegetariana tamaño mediana', 12.5, true, '/images/pizzas/vegetariana_medium.png', ARRAY['Salsa de tomate', 'Mozzarella']),
('personal', 'Vegetariana', 'Deliciosa pizza Vegetariana tamaño pequeña', 8.5, true, '/images/pizzas/vegetariana_personal.png', ARRAY['Salsa de tomate', 'Mozzarella']);
